name: Build Website
runs:
  using: "composite"
  steps:
    - name: Set Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
    - name: Set up Yarn2
      run: |
        corepack enable
        yarn set version berry
    - name: Run install
      uses: borales/actions-yarn@v5
      with:
        cmd: install # will run `yarn install` command
    - name: Build production bundle
      uses: borales/actions-yarn@v5
      with:
        cmd: build
